#!/usr/bin/env ruby

require File.expand_path('../../flashcard_tester.rb', __FILE__)

flashcards = {
  "A" => "Alfa",
  "B" => "Bravo",
  "C" => "Charlie",
  'D' => 'Delta',
  'E' => 'Echo',
  'F' => 'Foxtrot',
  'G' => 'Golf',
  'H' => 'Hotel',
  'I' => 'India',
  'J' => 'Juliet',
  'K' => 'Kilo',
  'L' => 'Lima',
  'M' => 'Mike',
  'N' => 'November',
  'O' => 'Oscar',
  'P' => 'Papa',
  'Q' => 'Quebec',
  'R' => 'Romeo',
  'S' => 'Sierra',
  'T' => 'Tango',
  'U' => 'Uniform',
  'V' => 'Victor',
  'W' => 'Whiskey',
  'X' => 'X-Ray',
  'Y' => 'Yankee',
  'Z' => 'Zulu'
}

FlashcardTester.new("NATO alphabet", ARGV[0], "Enter the telephony for the letter %s: ", flashcards)